### ISSUE TITLE
node on click event

### ISSUE THREAD

**Issue by roccomuso** [feross/p2p-graph#10]
- [ ] new method `.getPeer(...)`
- [ ] onClick event: `.getPeer(...).on('click', cb)`, better api in mind?

**Comment by rgolea** [comment]
@roccomuso I believe it's a great way to use the html. I did something like `rootElement.querySelectorAll('.node').forEach(...)` and for some reason I didn't think about it before. Will you be able to do it or should I?

**Comment by roccomuso** [comment]
@rgolea feel free to submit a PR.
